#!/bin/sh
set -e

delay_between_frames=3
frame_rate=10
version="1.2.1"

get_output_filename() {
  local file=$1
  local filename="${file##*/}"
  echo "${filename%%.*}.gif"
}

get_absolute_path() {
  local file=$1
  echo $(cd $(dirname $file) 2> /dev/null && pwd)
}

print_usage() {
  echo ""
  echo "usage: video2gif [options] <input file>"
  echo ""
  echo "options:"
  echo "  -s, --size     size. e.g 600x400. Default: same as video size"
  echo "  -o, --output   output file name. Default: [input].gif."
  echo "  -i, --input    input file."
  echo "  -ts, --start-time  time position from video to start gif. Seconds or HH:mm:ss. Default: start of the video"
  echo "  -te, --end-time    time position from video to stop gif. Seconds or HH:mm:ss. Default: end of the video"
  echo "  -h, --help     print this help message."
  echo "  -v, --version  print version."
  echo "  -fr, --video-frame-rate    video frame rate. Less frames, lighter gifs. Default: 10."
  echo "  -d, --gif-frame-duration   delay/duration of each Gif frame in hundredths of a second. Default: 3."
  echo ""
  echo "examples:"
  echo "  video2gif input.mov"
  echo "  video2gif -s 900x600 input.mov"
  echo "  video2gif -o output.gif input.mov"
  echo "  video2gif -o out.gif -i input.mov"
  echo "  video2gif --start-time 20:00 --end-time 20:30 input.mov"
  echo ""
}

print_help() {
  echo "video2gif"
  echo "converts video to gif using ffmpeg and gifsicle"

  print_usage
}

print_short_help() {
  printf "See 'video2gif --help'\\n"
}

print_version() {
  printf "video2gif $version\\n"
}

print_error() {
  printf "video2gif: %s\\n" "$@" >&2
}

check_argument() {
  if [ -z "$2" ]
  then
    print_error "value for '$1' not provided"
    exit 1
  fi
}

handle_with_docker() {
  input_file=$1
  output_file=$2
  shift
  shift

  while [ "$#" -gt 0 ]; do
    case "$1" in
      -i|--input|-o|--output)
        shift
        shift
        ;;
      -*)
        parameters="$parameters $1 $2" 
        shift
        shift
        ;;
      *) break;;
    esac
  done

  input_dirname=$(get_absolute_path $input_file)
  output_dirname=$(get_absolute_path $output_file)

  if [ -z "$input_dirname" ]; then
    print_error "input file ${input_file} does not exist"
    exit 1
  fi

  if [ -z "$output_dirname" ]; then
    print_error "output directory for ${output_file} does not exist"
    exit 1
  fi

  docker run --rm \
    -v ${output_dirname}:'/tmp/out' \
    -v ${input_dirname}:'/tmp/in' \
    vgerevini/video2gif:${version} \
    -o "/tmp/out/$(basename $output_file)" -i "/tmp/in/$(basename $input_file)" $parameters
}

all_parameters=$@
while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      print_help
      exit 0
      ;;
    -v|--version)
      print_version
      exit 0
      ;;
    -i|--input)
      input_file="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    -o|--output)
      output_file="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    -s|--size)
      output_size="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    -d|--gif-frame-duration)
      delay_between_frames="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    -fr|--video-frame-rate)
      frame_rate="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    -ts|--start-time)
      start_time="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    -te|--end-time)
      end_time="$2"
      check_argument $1 $2
      shift
      shift
      ;;
    --)
      shift
      break
      ;;
    -*)
      print_error "invalid option '$1'."
      print_short_help
      exit 1
      ;;
    *) break;;
  esac
done

if [ "$#" -eq 0 ] && [ -z "$input_file" ]; then
  print_error "input not provided"
  print_short_help
  exit 1
fi

if [ "$#" -gt 1 ] || ([ "$#" -gt 0 ] && [ ! -z "$input_file" ]); then
  print_error "command doesn't accept multiple inputs"
  print_short_help
  exit 1
fi

[ -z "$input_file" ] && input_file=$@
[ -z "$output_file" ] && output_file=$(get_output_filename $input_file)

if [ -x "$(command -v ffmpeg)" ] && [ -x "$(command -v gifsicle)" ]; then
  [ -n "$output_size" ] && output_size_parameter="-s $output_size"
  [ -n "$start_time" ] && start_time_parameter="-ss $start_time"
  [ -n "$end_time" ] && end_time_parameter="-to $end_time"

  echo "converting $input_file to $output_file..."

  ffmpeg $start_time_parameter $end_time_parameter \
    -i $input_file $output_size_parameter -r $frame_rate -f gif  - | \
    gifsicle --optimize=3 --delay=$delay_between_frames > $output_file

  printf "\nSUCCESS: $input_file converted\n\n"

elif [ -x "$(command -v docker)" ]; then
  handle_with_docker $input_file $output_file $all_parameters
else
  print_error "couldn't find required dependencies. \nthis script requires docker OR ffmpeg and gifsicle.\n"
  exit 1
fi

